
public enum MessageType {
    REGISTER,
    UNREGISTER,
    SEND_MESSAGE,
    REGISTER_APPROVED,
    REGISTER_DECLINED,
    UNREGISTER_APPROVED,
    UNREGISTER_DECLINED,
    MESSAGE_DECLINED,
    BROADCAST_MESSAGE
}
